image:
  file: .gitpod.Dockerfile


# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init:  python3 -m pip install -r  "/etc/ml/ml_zero_requirements.txt"
    command:  python3 src/warmup/main.py 

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
